# Generated by Django 4.2.7 on 2023-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_temperature_delete_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='preassure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('preassure', models.FloatField()),
            ],
        ),
    ]
